### ISSUE TITLE
Error in PyTorch DataLoder

### ISSUE THREAD

**Issue by MostafaMagdSalama** [sgrvinod/a-PyTorch-Tutorial-to-Super-Resolution#1]
i got this error when i train a model (srgan)

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
data = fetcher.fetch(index)
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/content/drive/My Drive/PyTorch--master/datasets.py", line 67, in getitem
img = Image.open(self.images[i], mode='r')
KeyError: 0
how how  many epoch i should do to make a good model?
i'm training the model in google colab
thanks

**Comment by goudantongxue** [comment]
for d in train_folders:
        for i in os.listdir(d):
            img_path = os.path.join(d, i)
            img = Image.open(img_path, mode='r')
            if img.width >= min_size and img.height >= min_size:
                train_images.append(img_path)

there is something wrong. For the first line, train folders is a string and so for d in train_folders doesn't work.

**Comment by goudantongxue** [comment]
> ```
> for d in train_folders:
>     for i in os.listdir(d):
>         img_path = os.path.join(d, i)
>         img = Image.open(img_path, mode='r')
>         if img.width >= min_size and img.height >= min_size:
>             train_images.append(img_path)
> ```
> 
> there is something wrong. For the first line, train folders is a string and so for d in train_folders doesn't works.

Sorry, now i know that d is a list. hahaha

**Comment by JIAZhenZ** [comment]
How can I download the training datasets? thanks

**Comment by lucidBrot** [comment]
@JIAZhenZ when you search (<kbd>CTRL</kbd><kbd>F</kbd>) in the readme for "download", you will find:

> Model checkpoints are available [here](https://drive.google.com/drive/folders/12OG-KawSFFs6Pah89V4a_Td-VcwMBE5i?usp=sharing).

> While the authors of the paper trained their models on a 350k-image subset of the ImageNet data, I simply used about 120k COCO images (train2014 and val2014 folders). They're a lot easier to obtain. If you wish to do the same, you can download them from the links listed in my o[ther tutorial.](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning#dataset)

So: [ [training direct link](http://images.cocodataset.org/zips/train2014.zip) ],  [[validation direct link](http://images.cocodataset.org/zips/val2014.zip)]
